services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=resource_requisition_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - resource_requisition_data:/var/lib/mysql

volumes:
  resource_requisition_data: 